Игра началась 💀
ZalyalovIldar/HW6ProtocolGame pull request #1
Opened 2016-10-28 07:49 UTC by Leklef

2016-10-29 09:50 UTC, ZalyalovIldar requested changes

2016-10-29 09:50 UTC, ZalyalovIldar commented on HWProtocolGame/BattleVC.h
> +@property(strong, nonatomic) Wizard *enemyWizard;
было бы отлично, если ты переделал бы на 2 проперти, 1 для того, кто атакует 2-ой для того, кто атакует :)

2016-10-29 09:50 UTC, ZalyalovIldar commented on HWProtocolGame/BattleVC.m
> +    NSString *message = [[NSString alloc]init];
тут логику соотвественно переделать постарайся под 2 проперти, слишком много всяких if-ов

2016-10-29 12:05 UTC, ZalyalovIldar commented
еще добавь init такой, чтобы можно было инициализировать юнита с определенными параметрами (ну чтобы мог выставить 100 хп и 20 силы атаки например), со всеми основными свойствами, и обязательно протестить, все ли ок, правильно ли работает атака.

2016-10-29 16:10 UTC, Leklef commented
Кто тут хочет подраться?!

2016-11-02 16:27 UTC, ZalyalovIldar approved these changes

2016-11-02 16:27 UTC, closed without merging